<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Version>0.1.0-alpha.1</Version>
    <AssemblyName>PrintCost</AssemblyName>
    <RootNamespace>PrintCost.Desktop</RootNamespace>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/PrintCost.Core/PrintCost.Core.csproj" /></ItemGroup>
</Project>
